[book]
authors = ["Tom Irgang"]
description = "All about long term supported embedded Linux solutions."
language = "de"
multilingual = false
src = "src"
title = "Tom.log"

[build]
create-missing = true

[preprocessor.image-size]
command = "mdbook-image-size"

[output.html]
additional-css = ["custom.css"]
default-theme = "dark"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = false
copy-fonts = true
git-repository-url = "https://github.com/tomirgang/tomirgang.github.io"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/tomirgang/tomirgang.github.io/edit/main/src/{path}"
cname = "tomirgang.de"
input-404 = "not-found.md"

[output.html.print]
enable = true
page-break = true

