[input]
base_directory = "output"
html_selector = "article"

[[input.files]]
path = "folien-mit-marp-in-vs-code.html"
url = "/folien-mit-marp-in-vs-code.html"
title = "Folien mit Marp in VS Code"

[[input.files]]
path = "folien-mit-revealjs.html"
url = "/folien-mit-revealjs.html"
title = "Folien mit Reveal.js"

[[input.files]]
path = "ein-blog-mit-pelikan.html"
url = "/ein-blog-mit-pelikan.html"
title = "Ein Blog mit Pelikan"